/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpcap_IPAddress */

#ifndef _Included_jpcap_IPAddress
#define _Included_jpcap_IPAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpcap_IPAddress
 * Method:    gethostnamenative
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpcap_IPAddress_gethostnamenative
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jpcap_IPAddress
 * Method:    gethostname6native
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpcap_IPAddress_gethostname6native
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jpcap_IPAddress
 * Method:    getaddr6native
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jpcap_IPAddress_getaddr6native
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
