/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpcap_JpcapSender */

#ifndef _Included_jpcap_JpcapSender
#define _Included_jpcap_JpcapSender
#ifdef __cplusplus
extern "C" {
#endif
#undef jpcap_JpcapSender_MAX_NUMBER_OF_INSTANCES
#define jpcap_JpcapSender_MAX_NUMBER_OF_INSTANCES 255L
/*
 * Class:     jpcap_JpcapSender
 * Method:    nativeOpenDevice
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpcap_JpcapSender_nativeOpenDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jpcap_JpcapSender
 * Method:    nativeSendPacket
 * Signature: (Ljpcap/packet/Packet;)V
 */
JNIEXPORT void JNICALL Java_jpcap_JpcapSender_nativeSendPacket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jpcap_JpcapSender
 * Method:    nativeCloseDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jpcap_JpcapSender_nativeCloseDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
