/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jpcap */

#ifndef _Included_Jpcap
#define _Included_Jpcap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jpcap
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Jpcap_close
  (JNIEnv *, jobject);

/*
 * Class:     Jpcap
 * Method:    getErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jpcap_getErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     Jpcap
 * Method:    getPacket
 * Signature: ()Ljpcap/Packet;
 */
JNIEXPORT jobject JNICALL Java_Jpcap_getPacket
  (JNIEnv *, jobject);

/*
 * Class:     Jpcap
 * Method:    lookupDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jpcap_lookupDevice
  (JNIEnv *, jclass);

/*
 * Class:     Jpcap
 * Method:    nativeOpenLive
 * Signature: (Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jpcap_nativeOpenLive
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     Jpcap
 * Method:    nativeOpenOffline
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jpcap_nativeOpenOffline
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Jpcap
 * Method:    processPacket
 * Signature: (ILjpcap/JpcapHandler;)I
 */
JNIEXPORT jint JNICALL Java_Jpcap_processPacket
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     Jpcap
 * Method:    setFilter
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_Jpcap_setFilter
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     Jpcap
 * Method:    updateStat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Jpcap_updateStat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
